[tool.poetry.dependencies]
tensorflow = "^2.12.0"
tensorflow-io-gcs-filesystem = "^0.31.0"
umap-learn = "^0.5.5"

[tool.poetry.group.dev.dependencies]
papermill = "^2.5.0"
nbqa = "^1.7.1"

sphinx = "^7.2.6"
sphinx-rtd-theme = "^2.0.0"


[tool.poe]
  [tool.poe.tasks.nbcheck]
  help = "Check notebooks for metadata"
  cmd = "nb-clean check . --preserve-cell-outputs --remove-empty-cells"

  [tool.poe.tasks.nbclean]
  help = "Clean notebook metadatas"
  sequence = [
    { cmd = "nbdev_clean --fname ." },
    { cmd = "nb-clean clean . --preserve-cell-outputs --remove-empty-cells"},
  ]


  [tool.poe.tasks.nbrun]
  help = "Run notebooks to see if they work"
  shell = """
    RED='\\033[0;31m'
    NC='\\033[0m' # No Color

    for input_file in $(find src -type f -name "*.ipynb"); do
      echo "${RED}Notebook: ${input_file}${NC}"
      papermill "$input_file" temp.ipynb
    done

    rm temp.ipynb
  """

  [tool.poe.tasks.nbqa]
  help = "Run all QA tools on notebooks"
  sequence = [
    { ref = "format" },
    { ref = "nbclean" },
    { ref = "nbcheck" },
    { ref = "nbrun" },
  ]
