name: CI

on: pull_request

jobs:
  qa-py:
    name: Python QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: uv run ruff format --check

#      - name: Linting
#        run: uv run ruff check

      - name: Notebooks - check for unnecessary metadata and empty cells
        run: uv run nb-clean check . --preserve-cell-outputs --remove-empty-cells

      - name: Unit tests
        run: uv run pytest --doctest-modules
